using FastScan.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using System.Text.Json.Serialization;
var builder = WebApplication.CreateBuilder(args);
var connectionString = builder.Configuration.GetConnectionString("FastScanDatabase") ?? Environment.GetEnvironmentVariable("MYSQL_URL");
if (string.IsNullOrWhiteSpace(connectionString)) throw new InvalidOperationException("Configurá ConnectionStrings__FastScanDatabase o MYSQL_URL.");
var jwtKey = builder.Configuration["Jwt:Key"] ?? throw new InvalidOperationException("Configurá Jwt__Key como secreto del entorno.");
builder.Services.AddDbContext<FastScanDbContext>(options => options.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString)));
builder.Services.AddCors(options => options.AddPolicy("FastScan", policy => policy.WithOrigins(builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? ["http://localhost:4200"]).AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options => options.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = true, ValidateAudience = true, ValidateLifetime = true, ValidateIssuerSigningKey = true, ValidIssuer = builder.Configuration["Jwt:Issuer"], ValidAudience = builder.Configuration["Jwt:Audience"], IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)) });
builder.Services.AddAuthorization(); builder.Services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter())); builder.Services.AddOpenApi();
var app = builder.Build(); app.MapOpenApi(); app.UseCors("FastScan"); app.UseAuthentication(); app.UseAuthorization(); app.MapControllers(); app.Run();
